/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as charityDonationSol from "./CharityDonation.sol";
export type { charityDonationSol };
export type { ContributorNFT } from "./ContributorNFT";
