/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export declare namespace CampaignDonation {
  export type DonationStruct = {
    donor: AddressLike;
    amount: BigNumberish;
    timestamp: BigNumberish;
  };

  export type DonationStructOutput = [
    donor: string,
    amount: bigint,
    timestamp: bigint
  ] & { donor: string; amount: bigint; timestamp: bigint };
}

export interface CampaignDonationInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "addCampaignUpdate"
      | "admins"
      | "approveTransaction"
      | "approvedSignatures"
      | "campaigns"
      | "contractOwner"
      | "contributorNFT"
      | "createCampaign"
      | "donateToCampaign"
      | "donations"
      | "getCampaignUpdates"
      | "getDonationHistory"
      | "requiredSignatures"
      | "rewardTopContributors"
      | "signers"
      | "transactionCount"
      | "transactions"
      | "updateCampaignStatus"
      | "withdrawFunds"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "CampaignCreated"
      | "CampaignStatusUpdated"
      | "CampaignUpdated"
      | "DonationReceived"
      | "TopContributorsRewarded"
      | "TransactionApproved"
      | "TransactionCreated"
      | "TransactionExecuted"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "addCampaignUpdate",
    values: [BigNumberish, string]
  ): string;
  encodeFunctionData(functionFragment: "admins", values: [AddressLike]): string;
  encodeFunctionData(
    functionFragment: "approveTransaction",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "approvedSignatures",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "campaigns",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "contractOwner",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "contributorNFT",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "createCampaign",
    values: [string, string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "donateToCampaign",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "donations",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getCampaignUpdates",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getDonationHistory",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "requiredSignatures",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "rewardTopContributors",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "signers",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "transactionCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transactions",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "updateCampaignStatus",
    values: [BigNumberish, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawFunds",
    values: [BigNumberish, BigNumberish, AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "addCampaignUpdate",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "admins", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "approveTransaction",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "approvedSignatures",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "campaigns", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "contractOwner",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "contributorNFT",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createCampaign",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "donateToCampaign",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "donations", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getCampaignUpdates",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getDonationHistory",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "requiredSignatures",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "rewardTopContributors",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "signers", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "transactionCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transactions",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateCampaignStatus",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "withdrawFunds",
    data: BytesLike
  ): Result;
}

export namespace CampaignCreatedEvent {
  export type InputTuple = [
    id: BigNumberish,
    creator: AddressLike,
    title: string,
    targetAmount: BigNumberish
  ];
  export type OutputTuple = [
    id: bigint,
    creator: string,
    title: string,
    targetAmount: bigint
  ];
  export interface OutputObject {
    id: bigint;
    creator: string;
    title: string;
    targetAmount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace CampaignStatusUpdatedEvent {
  export type InputTuple = [id: BigNumberish, active: boolean];
  export type OutputTuple = [id: bigint, active: boolean];
  export interface OutputObject {
    id: bigint;
    active: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace CampaignUpdatedEvent {
  export type InputTuple = [id: BigNumberish, updateMessage: string];
  export type OutputTuple = [id: bigint, updateMessage: string];
  export interface OutputObject {
    id: bigint;
    updateMessage: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DonationReceivedEvent {
  export type InputTuple = [
    campaignId: BigNumberish,
    donor: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [campaignId: bigint, donor: string, amount: bigint];
  export interface OutputObject {
    campaignId: bigint;
    donor: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TopContributorsRewardedEvent {
  export type InputTuple = [
    campaignId: BigNumberish,
    topContributors: AddressLike[]
  ];
  export type OutputTuple = [campaignId: bigint, topContributors: string[]];
  export interface OutputObject {
    campaignId: bigint;
    topContributors: string[];
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TransactionApprovedEvent {
  export type InputTuple = [txId: BigNumberish, signer: AddressLike];
  export type OutputTuple = [txId: bigint, signer: string];
  export interface OutputObject {
    txId: bigint;
    signer: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TransactionCreatedEvent {
  export type InputTuple = [
    txId: BigNumberish,
    recipient: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [txId: bigint, recipient: string, amount: bigint];
  export interface OutputObject {
    txId: bigint;
    recipient: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TransactionExecutedEvent {
  export type InputTuple = [
    txId: BigNumberish,
    recipient: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [txId: bigint, recipient: string, amount: bigint];
  export interface OutputObject {
    txId: bigint;
    recipient: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface CampaignDonation extends BaseContract {
  connect(runner?: ContractRunner | null): CampaignDonation;
  waitForDeployment(): Promise<this>;

  interface: CampaignDonationInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  addCampaignUpdate: TypedContractMethod<
    [_id: BigNumberish, _updateMessage: string],
    [void],
    "nonpayable"
  >;

  admins: TypedContractMethod<[arg0: AddressLike], [boolean], "view">;

  approveTransaction: TypedContractMethod<
    [_txId: BigNumberish],
    [void],
    "nonpayable"
  >;

  approvedSignatures: TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike],
    [boolean],
    "view"
  >;

  campaigns: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, string, string, string, bigint, bigint, boolean] & {
        id: bigint;
        creator: string;
        title: string;
        description: string;
        targetAmount: bigint;
        totalDonated: bigint;
        active: boolean;
      }
    ],
    "view"
  >;

  contractOwner: TypedContractMethod<[], [string], "view">;

  contributorNFT: TypedContractMethod<[], [string], "view">;

  createCampaign: TypedContractMethod<
    [_title: string, _description: string, _targetAmount: BigNumberish],
    [void],
    "nonpayable"
  >;

  donateToCampaign: TypedContractMethod<[_id: BigNumberish], [void], "payable">;

  donations: TypedContractMethod<
    [arg0: BigNumberish, arg1: BigNumberish],
    [
      [string, bigint, bigint] & {
        donor: string;
        amount: bigint;
        timestamp: bigint;
      }
    ],
    "view"
  >;

  getCampaignUpdates: TypedContractMethod<
    [_id: BigNumberish],
    [string[]],
    "view"
  >;

  getDonationHistory: TypedContractMethod<
    [_id: BigNumberish],
    [CampaignDonation.DonationStructOutput[]],
    "view"
  >;

  requiredSignatures: TypedContractMethod<[], [bigint], "view">;

  rewardTopContributors: TypedContractMethod<
    [_campaignId: BigNumberish],
    [void],
    "nonpayable"
  >;

  signers: TypedContractMethod<[arg0: AddressLike], [boolean], "view">;

  transactionCount: TypedContractMethod<[], [bigint], "view">;

  transactions: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, string, boolean, bigint] & {
        amount: bigint;
        recipient: string;
        executed: boolean;
        approvals: bigint;
      }
    ],
    "view"
  >;

  updateCampaignStatus: TypedContractMethod<
    [_id: BigNumberish, _active: boolean],
    [void],
    "nonpayable"
  >;

  withdrawFunds: TypedContractMethod<
    [_campaignId: BigNumberish, _amount: BigNumberish, _recipient: AddressLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "addCampaignUpdate"
  ): TypedContractMethod<
    [_id: BigNumberish, _updateMessage: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "admins"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "approveTransaction"
  ): TypedContractMethod<[_txId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "approvedSignatures"
  ): TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "campaigns"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, string, string, string, bigint, bigint, boolean] & {
        id: bigint;
        creator: string;
        title: string;
        description: string;
        targetAmount: bigint;
        totalDonated: bigint;
        active: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "contractOwner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "contributorNFT"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "createCampaign"
  ): TypedContractMethod<
    [_title: string, _description: string, _targetAmount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "donateToCampaign"
  ): TypedContractMethod<[_id: BigNumberish], [void], "payable">;
  getFunction(
    nameOrSignature: "donations"
  ): TypedContractMethod<
    [arg0: BigNumberish, arg1: BigNumberish],
    [
      [string, bigint, bigint] & {
        donor: string;
        amount: bigint;
        timestamp: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getCampaignUpdates"
  ): TypedContractMethod<[_id: BigNumberish], [string[]], "view">;
  getFunction(
    nameOrSignature: "getDonationHistory"
  ): TypedContractMethod<
    [_id: BigNumberish],
    [CampaignDonation.DonationStructOutput[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "requiredSignatures"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "rewardTopContributors"
  ): TypedContractMethod<[_campaignId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "signers"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "transactionCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "transactions"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, string, boolean, bigint] & {
        amount: bigint;
        recipient: string;
        executed: boolean;
        approvals: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "updateCampaignStatus"
  ): TypedContractMethod<
    [_id: BigNumberish, _active: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "withdrawFunds"
  ): TypedContractMethod<
    [_campaignId: BigNumberish, _amount: BigNumberish, _recipient: AddressLike],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "CampaignCreated"
  ): TypedContractEvent<
    CampaignCreatedEvent.InputTuple,
    CampaignCreatedEvent.OutputTuple,
    CampaignCreatedEvent.OutputObject
  >;
  getEvent(
    key: "CampaignStatusUpdated"
  ): TypedContractEvent<
    CampaignStatusUpdatedEvent.InputTuple,
    CampaignStatusUpdatedEvent.OutputTuple,
    CampaignStatusUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "CampaignUpdated"
  ): TypedContractEvent<
    CampaignUpdatedEvent.InputTuple,
    CampaignUpdatedEvent.OutputTuple,
    CampaignUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "DonationReceived"
  ): TypedContractEvent<
    DonationReceivedEvent.InputTuple,
    DonationReceivedEvent.OutputTuple,
    DonationReceivedEvent.OutputObject
  >;
  getEvent(
    key: "TopContributorsRewarded"
  ): TypedContractEvent<
    TopContributorsRewardedEvent.InputTuple,
    TopContributorsRewardedEvent.OutputTuple,
    TopContributorsRewardedEvent.OutputObject
  >;
  getEvent(
    key: "TransactionApproved"
  ): TypedContractEvent<
    TransactionApprovedEvent.InputTuple,
    TransactionApprovedEvent.OutputTuple,
    TransactionApprovedEvent.OutputObject
  >;
  getEvent(
    key: "TransactionCreated"
  ): TypedContractEvent<
    TransactionCreatedEvent.InputTuple,
    TransactionCreatedEvent.OutputTuple,
    TransactionCreatedEvent.OutputObject
  >;
  getEvent(
    key: "TransactionExecuted"
  ): TypedContractEvent<
    TransactionExecutedEvent.InputTuple,
    TransactionExecutedEvent.OutputTuple,
    TransactionExecutedEvent.OutputObject
  >;

  filters: {
    "CampaignCreated(uint256,address,string,uint256)": TypedContractEvent<
      CampaignCreatedEvent.InputTuple,
      CampaignCreatedEvent.OutputTuple,
      CampaignCreatedEvent.OutputObject
    >;
    CampaignCreated: TypedContractEvent<
      CampaignCreatedEvent.InputTuple,
      CampaignCreatedEvent.OutputTuple,
      CampaignCreatedEvent.OutputObject
    >;

    "CampaignStatusUpdated(uint256,bool)": TypedContractEvent<
      CampaignStatusUpdatedEvent.InputTuple,
      CampaignStatusUpdatedEvent.OutputTuple,
      CampaignStatusUpdatedEvent.OutputObject
    >;
    CampaignStatusUpdated: TypedContractEvent<
      CampaignStatusUpdatedEvent.InputTuple,
      CampaignStatusUpdatedEvent.OutputTuple,
      CampaignStatusUpdatedEvent.OutputObject
    >;

    "CampaignUpdated(uint256,string)": TypedContractEvent<
      CampaignUpdatedEvent.InputTuple,
      CampaignUpdatedEvent.OutputTuple,
      CampaignUpdatedEvent.OutputObject
    >;
    CampaignUpdated: TypedContractEvent<
      CampaignUpdatedEvent.InputTuple,
      CampaignUpdatedEvent.OutputTuple,
      CampaignUpdatedEvent.OutputObject
    >;

    "DonationReceived(uint256,address,uint256)": TypedContractEvent<
      DonationReceivedEvent.InputTuple,
      DonationReceivedEvent.OutputTuple,
      DonationReceivedEvent.OutputObject
    >;
    DonationReceived: TypedContractEvent<
      DonationReceivedEvent.InputTuple,
      DonationReceivedEvent.OutputTuple,
      DonationReceivedEvent.OutputObject
    >;

    "TopContributorsRewarded(uint256,address[])": TypedContractEvent<
      TopContributorsRewardedEvent.InputTuple,
      TopContributorsRewardedEvent.OutputTuple,
      TopContributorsRewardedEvent.OutputObject
    >;
    TopContributorsRewarded: TypedContractEvent<
      TopContributorsRewardedEvent.InputTuple,
      TopContributorsRewardedEvent.OutputTuple,
      TopContributorsRewardedEvent.OutputObject
    >;

    "TransactionApproved(uint256,address)": TypedContractEvent<
      TransactionApprovedEvent.InputTuple,
      TransactionApprovedEvent.OutputTuple,
      TransactionApprovedEvent.OutputObject
    >;
    TransactionApproved: TypedContractEvent<
      TransactionApprovedEvent.InputTuple,
      TransactionApprovedEvent.OutputTuple,
      TransactionApprovedEvent.OutputObject
    >;

    "TransactionCreated(uint256,address,uint256)": TypedContractEvent<
      TransactionCreatedEvent.InputTuple,
      TransactionCreatedEvent.OutputTuple,
      TransactionCreatedEvent.OutputObject
    >;
    TransactionCreated: TypedContractEvent<
      TransactionCreatedEvent.InputTuple,
      TransactionCreatedEvent.OutputTuple,
      TransactionCreatedEvent.OutputObject
    >;

    "TransactionExecuted(uint256,address,uint256)": TypedContractEvent<
      TransactionExecutedEvent.InputTuple,
      TransactionExecutedEvent.OutputTuple,
      TransactionExecutedEvent.OutputObject
    >;
    TransactionExecuted: TypedContractEvent<
      TransactionExecutedEvent.InputTuple,
      TransactionExecutedEvent.OutputTuple,
      TransactionExecutedEvent.OutputObject
    >;
  };
}
