/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as charityDonationSol from "./CharityDonation.sol";
export { ContributorNFT__factory } from "./ContributorNFT__factory";
