/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { CampaignDonation } from "./CampaignDonation";
export * as factories from "./factories";
export { CampaignDonation__factory } from "./factories/CampaignDonation__factory";
